name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Problem Matcher
        uses: xt0rted/markdownlint-problem-matcher@v1
      - name: Run Markdownlint
        run: npx --package markdownlint-cli markdownlint '**/*.md'
